### ISSUE TITLE
Are there any releases for this?

### ISSUE THREAD

**Issue by InfernoDigital** [Sorenon/TitleWorlds#3]
Its a recommended install along with mcxr but it says there aren't any releases yet.

**Comment by Flamgop** [comment]
You can download the latest artifact with gh actions at https://github.com/Sorenon/TitleWorlds/actions

**Comment by InfernoDigital** [comment]
I am not a programmer, Im a technical artist but I don't use git very often so could you explain how to do that? That would be a big help

**Comment by Flamgop** [comment]
When you goto actions, click on the latest build (It says [implement a '3D Screenshot' command](https://github.com/Sorenon/TitleWorlds/actions/runs/1941781082)) and scroll down until you see an item that says "Artifacts", click on that and it will contain the TitleWorlds jar

**Comment by Sorenon** [comment]
https://modrinth.com/mod/titleworlds
