### ISSUE TITLE
titlewolds failing for unknown reason.

### ISSUE THREAD

**Issue by IzzyDotExe** [Sorenon/TitleWorlds#4]
After the second time launching with titleworlds it gives me an error saying failed to connect to server. 

error:
![image](https://user-images.githubusercontent.com/44146685/168483242-7f12693e-6417-4647-b421-88a3f836550e.png)

[latest.log](https://github.com/Sorenon/TitleWorlds/files/8695393/latest.log)

tw folder
![image](https://user-images.githubusercontent.com/44146685/168483289-858c0d73-60ce-4f83-a72f-a1f7875d6c7c.png)

**Comment by Sorenon** [comment]
Thank you, I was hoping someone would report this

It's an error I get about 0.1% of the time when developing so it is a pain to debug it but this customized crashlog should make it easier
