### ISSUE TITLE
1.19 support

### ISSUE THREAD

**Issue by NotNite** [Sorenon/TitleWorlds#6]

**Comment by thejudge156** [comment]
Latest release supports 1.19

**Comment by NotNite** [comment]
Really? I'm getting [a crash](https://mclo.gs/VyQ6BCR) in my instance (other QoL mods disabled, just mcxr + titleworlds + fabric API).

**Comment by Fishvap** [comment]
I'm pretty sure Titleworlds hasn't been updated yet.

**Comment by Flopgop** [comment]
> Really? I'm getting [a crash](https://mclo.gs/VyQ6BCR) in my instance (other QoL mods disabled, just mcxr + titleworlds + fabric API).

You can use the one on the QCXR github (specifically the [1.19 fork](https://github.com/QuestCraftPlusPlus/TitleWorlds/actions/runs/2456403759)) which works

**Comment by NotNite** [comment]
Thanks!
